=== Qadriga/tuer_server/ConfigSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/ConfigSchema" xmlns:tns="http://www.example.org/ConfigSchema" elementFormDefault="qualified">

    <element name="root">
    	<complexType>
    		<sequence>
    			<element name="SSHUSERNAME" type="string"></element>
    			<element name="sshkeyfilepath" type="string"></element>
    			<element name="REMOTEDATABASEUSERNAME" type="string"></element>
    			<element name="REMOTEDATABASEPASSWORD" type="string"></element>
    			<element name="REMOTEDATABASENAME" type="string"></element>
    			<element name="LOCALDATABASENAME" type="string"></element>
    			<element name="LOCALDATABASEUSERNAME" type="string"></element>
    			<element name="LOCALDATABASEPASSWORD" type="string"></element>
    			<element name="DOORID" type="int"></element>
    			<element name="SSHREMOTENAME" type="string"></element>
    			<element name="SSHTUNNELNAME" type="string"></element>
    		</sequence>
    	</complexType>
    </element>
</schema>

=== Qadriga/tuer_server/config.xml
<?xml version="1.0" encoding="UTF-8"
		?>
<root xmlns="http://www.example.org/ConfigSchema" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:schemaLocation="http://www.example.org/ConfigSchema ConfigSchema.xsd">
  <SSHUSERNAME>SSH User of the Day</SSHUSERNAME>
  <sshkeyfilepath>/path/to/file</sshkeyfilepath>
  <REMOTEDATABASEUSERNAME>Databaseuser1</REMOTEDATABASEUSERNAME>
  <REMOTEDATABASEPASSWORD>PASSWORD</REMOTEDATABASEPASSWORD>
  <REMOTEDATABASENAME>Database1</REMOTEDATABASENAME>
  <LOCALDATABASENAME>door</LOCALDATABASENAME>
  <LOCALDATABASEUSERNAME>pi</LOCALDATABASEUSERNAME>
  <LOCALDATABASEPASSWORD>Suppengr√ºn</LOCALDATABASEPASSWORD>
  <DOORID>010</DOORID>
  <SSHREMOTENAME>example.com</SSHREMOTENAME>
  <SSHTUNNELNAME>dbtunnel.1</SSHTUNNELNAME>
</root>
